---
title: "Primer reporte en R Markdown"
author: "Elisa Casares 137843"
output: html_document
---

### Introducci??n al formato R MArkdown

Ejemplo elaborado en `r date()`.

```{r Paquetes}
library(ggmap)
```

```{r GenerarDatos, message=FALSE}
# Llenar informaci??n (s??lo lo que est?? entre "").
clave.unica <- rep("137843", 3)
# 1: Si es mixto, o: no lo es.
es.mixto <- c(universidad = 1, preparatoria = 1, secundaria = 1)
# Llenar con la direcci??n.
universidad <- geocode("ITAM")
preparatoria <- geocode("Tecnol??gico de Monterrey, Campus Santa Fe")
secundaria <- geocode("Av. Centenario 1196, ??lvaro Obreg??n, M??xico DF")
# Generamos la informaci??n
educacion <- rbind(universidad, preparatoria, secundaria)
educacion <- cbind(clave.unica, es.mixto, educacion)
```

```{r Obtenci??nCoordenadasYMapas, warning=FALSE, message=FALSE}
limites <- make_bbox(lon, lat, educacion, f = 0.7)
mapa <- get_map(location = limites,
                maptype = "roadmap",
                source = "google")
```

```{r GraficarLocalizaciones, echo=FALSE}
ggmap(mapa) +
  geom_point(data = educacion,
             aes(x = lon, y = lat),
             size = 4, alpha = 0.6, colour = "red")
```
